### ISSUE TITLE
AGS 3.6.0 support

### ISSUE THREAD

**Issue by edmundito** [edmundito/ags-tween#18]
3.6.0 RC Thread:
https://www.adventuregamestudio.co.uk/forums/ags-engine-editor-releases/ags-3-6-0-release-candidate-rc1/

## TODO

- [x] `Object.Scaling`
- [x] `Character.AnimationVolume`
- [x] `GUIControl.Transparency`
- [x] `Overlay.X/Y` (Predates 3.6.0 but Overlays have never been supported)
- [x] `Overlay.Width/Height`
- [x] `Overlay.Transparency`
- [x] No limit on `Character.Scaling`
- [x] #17
- [x] Review changelog
- [x] Update docs
- [x] Bump version
- [x] Release

**Comment by ivan-mogilko** [comment]
Additionally from 3.6.0 RC, I think following new properties may be tweened:
- Character.AnimationVolume
- GUIControl.Transparency
- Overlay.Width and Height (scales overlay graphic)
- Overlay.Transparency
- Overlay.ZOrder? idk if you scale z-order of the objects, characters and gui.

**Comment by edmundito** [comment]
@ivan-mogilko Thanks! I'm glad to hear it has reached RC status, and this encourages me to add support to the new features.
